spring:
  application:
    name: user-federation-service
  main:
    banner-mode: "console"

server:
  port: 8080

logging:
  config: classpath:log4j2-spring.xml

app:
  keycloak:
    base-url: https://keycloak-4aay.onrender.com
    admin-realm: mi-realm
    source-realm: mi-realm
    target-realm: criptoactivos
    client-id: admin-cli-m2m
    client-secret: tfN3WkpXC8eR7ghXX3FNKxftOhvpLOaT
